title: 日暮秋烟下的博客
description: 计算机视觉｜RISC-V｜嵌入式开发
author: Shan Zhi

# 极简主题 绝对不报错 立刻显示新版
theme: minima

lang: zh-CN
timezone: Asia/Shanghai

url: "https://woshanzhi.github.io"
baseurl: ""

paginate: 10
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
      author: "Shan Zhi"
