title: 日暮秋烟起的博客
description: 计算机视觉｜RISC-V｜嵌入式开发
author: Shan Zhi

theme: minima

lang: zh-CN
timezone: Asia/Shanghai

url: "https://woshanzhi.github.io"
baseurl: ""

paginate: 10
paginate_path: "/page:num/"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
    values:
      layout: post
      author: Shan Zhi

# 如果不需要顶部导航可以注释掉
# header_pages:
#   - _tabs/about.md